name: Build Inference Providers PR Documentation

on:
  pull_request:
    paths:
      - "docs/inference-providers/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_pr_documentation.yml@6a5a6d1ecfa094768def72858d14d14e37853449  # huggingface/doc-builder#791 (InferenceSnippet prerender fix; main + 1)
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.number }}
      package: hub-docs
      package_name: inference-providers
      path_to_docs: hub-docs/docs/inference-providers/
      additional_args: --not_python_module
