name: Build documentation

on:
  push:
    paths:
      - "docs/hub/**"
    branches:
      - main

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: hub-docs
      package_name: hub
      path_to_docs: hub-docs/docs/hub/
      additional_args: --not_python_module
      custom_container: "" # no need for transformer's docker image
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
