name: Build SageMaker Documentation

on:
  push:
    branches:
      - main
      - doc-builder*
    paths:
      - docs/sagemaker/**
      - .github/workflows/sagemaker_build_documentation.yaml

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: hub-docs
      package_name: sagemaker
      path_to_docs: hub-docs/docs/sagemaker/source
      additional_args: --not_python_module
      pre_command: cd hub-docs/docs/sagemaker && make docs
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
